name: Build and Publish Docker image webapp
on:
  push:
    branches: 
      - develop
    paths:
      - "webapp/project"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create Docker images 
        run: docker-compose build webapp
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag images
        run: |
          docker tag education_social_network_webapp ${{ secrets.DOCKERHUB_USERNAME }}/education_social_network_webapp:latest
      - name: Push images to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/education_social_network_webapp:latest